services:
    app.twig_extension:
        class: UKMNorge\DesignBundle\Twig\DesignBundleExtension
        public: false
        tags:
            - { name: twig.extension }
    ukmdesign: 
        class: UKMNorge\DesignBundle\Services\UKMDesign
        public: true
        arguments: [@logger]